#!/usr/bin/env python3
"""Copy the slice of omni_sim_core the browser page needs, verbatim.

Two outputs from one source of truth:

    omni_sim_web/py/omni_sim_core/...   a plain copy, for reading and diffing
    omni_sim_web/js/core-bundle.js      the same sources as a JS object

The second exists because of the no-server rule. A page opened with ``file://``
cannot ``fetch()`` its own sibling files -- Chrome treats the file origin as
opaque and blocks it -- so the Python sources cannot be read at run time. A
``<script src>`` is not subject to that, so the sources ride in as JavaScript
and are written into Pyodide's virtual filesystem from memory.

What gets copied is deliberately small. ``mechanism/derive`` needs only
``math`` and ``mechanism/schema``; ``mechanism/jacobian`` adds numpy. Every
``__init__.py`` in the chain is empty, so importing them drags in nothing else
-- no ruamel, no scipy, no simulator. Widening this list is how the page stops
loading in two seconds, so the list is explicit rather than a glob.

Copies are byte-for-byte: the drift guard (``omni_sim_web/tests/
test_web_bundle.py``) compares hashes, and a copy that has been "fixed up" for
the browser would pass review and fail that test, which is the intent.

    scripts/sync_web_core.sh          # or: python scripts/sync_web_core.py
"""
from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "omni_sim_core" / "src"
WEB = ROOT / "omni_sim_web"

# Explicit, not a glob: every module here is one the chassis page actually
# imports, and each one added costs load time for every visitor.
MODULES = [
    "omni_sim_core/__init__.py",
    "omni_sim_core/mechanism/__init__.py",
    "omni_sim_core/mechanism/schema.py",
    "omni_sim_core/mechanism/derive.py",
    "omni_sim_core/mechanism/jacobian.py",
]

# Motor presets, converted to JSON here so the browser needs no YAML parser.
PRESET_DIR = ROOT / "config" / "presets" / "motors"

# The real robot's wheel layout. The page is a *chassis* page; inventing a
# layout for it would have meant the browser showing a machine nobody is
# building, and would have hidden the fact that the shipped one has its wheel
# positions rotated 90 deg against its drive axes.
CHASSIS_YAML = ROOT / "config" / "robot" / "chassis.yaml"


def _read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def _sha(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()[:16]


def collect() -> tuple[dict[str, str], dict[str, str]]:
    sources, hashes = {}, {}
    for rel in MODULES:
        src = SRC / rel
        if not src.exists():
            raise SystemExit(f"missing source: {src}")
        text = _read(src)
        sources[rel] = text
        hashes[rel] = _sha(text)
    return sources, hashes


def collect_presets() -> dict[str, dict]:
    import yaml

    out = {}
    for path in sorted(PRESET_DIR.glob("*.yaml")):
        out[path.stem] = yaml.safe_load(_read(path))
    return out


def write_copy(sources: dict[str, str]) -> None:
    for rel, text in sources.items():
        dest = WEB / "py" / rel
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(text, encoding="utf-8")


def collect_chassis() -> dict:
    import yaml

    return yaml.safe_load(_read(CHASSIS_YAML))


def write_bundle(sources: dict[str, str], hashes: dict[str, str],
                 presets: dict[str, dict], chassis: dict) -> Path:
    payload = {
        "generated_from": "omni_sim_core/src",
        "modules": sources,
        "hashes": hashes,
        "presets": presets,
        "chassis": chassis,
    }
    dest = WEB / "js" / "core-bundle.js"
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(
        "// GENERATED by scripts/sync_web_core.py -- do not edit.\n"
        "// The Python sources below are byte-for-byte copies of\n"
        "// omni_sim_core/src/omni_sim_core/**. They ride in as JavaScript\n"
        "// because a file:// page cannot fetch() its own sibling files.\n"
        "// Re-run the sync script after changing anything under mechanism/.\n"
        "window.OMNI_SIM_CORE = " + json.dumps(payload, ensure_ascii=False) + ";\n",
        encoding="utf-8")
    return dest


def main() -> int:
    sources, hashes = collect()
    presets = collect_presets()
    chassis = collect_chassis()
    write_copy(sources)
    bundle = write_bundle(sources, hashes, presets, chassis)
    total = sum(len(s) for s in sources.values())
    print(f"synced {len(sources)} modules ({total / 1024:.1f} kB) "
          f"+ {len(presets)} motor presets "
          f"+ {len(chassis['drive_wheels'])}-wheel chassis")
    for rel, h in hashes.items():
        print(f"  {h}  {rel}")
    print(f"-> {bundle.relative_to(ROOT)} ({bundle.stat().st_size / 1024:.1f} kB)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
