"""Build generated plant files from the robot description.

Input : ``config/robot/{chassis,actuators,model_error}.yaml`` +
        ``config/presets/motors/*.yaml``.
Output: ``config/generated/plant_true.yaml`` (MotorParams-shaped),
        ``config/generated/plant_nominal.yaml`` (NominalModel-shaped) and
        ``config/generated/jacobian.yaml`` (drive jacobian, for cross-checking).

The hand-written ``config/plant_true.yaml`` / ``config/plant_nominal.yaml`` are
NEVER touched. Generated files carry a GENERATED header, and any field whose
value was estimated rather than derived from a datasheet gets an inline
``# ESTIMATED`` comment so estimated and measured values are never silently
mixed.

Note: the current MotorParams plant is homogeneous (identical motors). A
representative drive motor (the first wheel by default) is used for the true
plant; per-wheel heterogeneity is a future extension.
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

from ruamel.yaml.comments import CommentedMap

from .derive import DerivedMotor, derive_motor
from .jacobian import DriveJacobian
from .schema import (ActuatorSet, Chassis, ModelError, MotorPreset)
from .yaml_rt import rt_dump, rt_load

GENERATED_HEADER = (
    "GENERATED by omni_sim_core.mechanism.build -- do not edit by hand.\n"
    "Source: config/robot/*.yaml + config/presets/motors/*.yaml.\n"
    "Regenerate with:  python tools/build_plant.py\n"
    "Hand-written config/plant_*.yaml are separate and are never overwritten."
)


@dataclass
class BuildInputs:
    chassis: Chassis
    actuators: ActuatorSet
    model_error: ModelError
    presets: dict[str, MotorPreset]
    base_dir: Path


def load_presets(presets_dir: str | Path) -> dict[str, MotorPreset]:
    presets_dir = Path(presets_dir)
    out: dict[str, MotorPreset] = {}
    for path in sorted(presets_dir.glob("*.yaml")):
        out[path.stem] = MotorPreset.from_doc(rt_load(path), path.stem)
    return out


def load_inputs(base_dir: str | Path) -> BuildInputs:
    base = Path(base_dir)
    robot = base / "config" / "robot"
    return BuildInputs(
        chassis=Chassis.from_doc(rt_load(robot / "chassis.yaml")),
        actuators=ActuatorSet.from_doc(rt_load(robot / "actuators.yaml")),
        model_error=ModelError.from_doc(rt_load(robot / "model_error.yaml")),
        presets=load_presets(base / "config" / "presets" / "motors"),
        base_dir=base,
    )


# datasheet fields an override may target (merged before deriving); anything
# else in an actuator's overrides is a final MotorParams-level value.
DATASHEET_OVERRIDE_KEYS = frozenset({
    "rated_voltage_v", "kv_rpm_per_v", "stall_torque_nm", "stall_current_a",
    "no_load_speed_rpm", "no_load_current_a", "rotor_inertia_kgm2", "encoder_cpr",
})


def _split_overrides(overrides: dict) -> tuple[dict, dict]:
    ds = {k: v for k, v in overrides.items() if k in DATASHEET_OVERRIDE_KEYS}
    param = {k: v for k, v in overrides.items() if k not in DATASHEET_OVERRIDE_KEYS}
    return ds, param


def _resolve_actuator(inp: BuildInputs, ref: str):
    """Return (datasheet, physical, overrides) for an actuator reference."""
    if ref not in inp.actuators.actuators:
        raise KeyError(f"chassis references actuator '{ref}' which is not "
                       "defined in actuators.yaml")
    adef = inp.actuators.actuators[ref]
    if adef.preset is not None:
        if adef.preset not in inp.presets:
            raise KeyError(f"actuator '{ref}' references unknown preset "
                           f"'{adef.preset}'")
        preset = inp.presets[adef.preset]
        return preset.datasheet, preset.physical, adef.overrides
    return adef.datasheet, None, adef.overrides


def derive_reference_motor(inp: BuildInputs) -> tuple[DerivedMotor, dict, "object"]:
    """Derive the representative drive motor (first wheel) and its overrides."""
    from dataclasses import replace
    from .schema import Physical
    wheel = inp.chassis.drive_wheels[0]
    datasheet, physical, overrides = _resolve_actuator(inp, wheel.actuator_ref)
    physical = physical or Physical()

    # Overrides are a flat dict; keys that name datasheet fields are merged BEFORE
    # deriving (so e.g. a corrected KV re-derives Kt), the rest are applied to the
    # final MotorParams AFTER deriving (e.g. a measured inertia_kgm2 for unit
    # variation). This matches both the section 4.2 example and section 6.3.
    ds_over, param_over = _split_overrides(dict(overrides))
    if ds_over:
        datasheet = replace(datasheet, **ds_over)

    n_wheels = len(inp.chassis.drive_wheels)
    mass_share = inp.chassis.center_of_mass.mass_kg / n_wheels
    # wheel-side load inertia = m_share * r^2 (wheel's own rotational inertia is
    # not known from the datasheet and is neglected here -- documented estimate).
    load_inertia = mass_share * wheel.radius_m ** 2

    derived = derive_motor(datasheet, physical,
                           gear_ratio=wheel.gear_ratio,
                           load_inertia_wheel_side_kgm2=load_inertia)
    return derived, param_over, wheel


def _motor_params_map(inp: BuildInputs) -> CommentedMap:
    derived, overrides, wheel = derive_reference_motor(inp)
    n_wheels = len(inp.chassis.drive_wheels)

    params: dict[str, Any] = {
        "n_motors": n_wheels,
        "inertia_kgm2": float(derived.reflected_inertia_kgm2),
        "damping_nms": float(derived.damping_nms),
        "torque_constant_nm_a": float(derived.torque_constant_nm_a),
        "resistance_ohm": float(derived.resistance_ohm),
        "back_emf_v_s": float(derived.back_emf_v_s),
        "enable_electrical_dynamics": False,
        "friction_coulomb_nm": 0.0,   # not available from datasheet
        "friction_static_nm": 0.0,
        "torque_max_nm": float(derived.stall_torque_nm),
        "omega_max_rad_s": float(derived.no_load_speed_rad_s),
    }
    if derived.inductance_h is not None:
        params["inductance_h"] = float(derived.inductance_h)

    # which params trace back to an estimated quantity
    estimated_fields: set[str] = set()
    if "reflected_inertia_kgm2" in derived.estimated:
        estimated_fields.add("inertia_kgm2")
    if "damping_nms" in derived.estimated:
        estimated_fields.add("damping_nms")

    # user overrides win and are, by definition, measured (not estimated)
    for k, v in overrides.items():
        params[k] = v
        estimated_fields.discard(k)

    cm = CommentedMap(params)
    cm.yaml_set_start_comment(
        GENERATED_HEADER
        + f"\nRepresentative drive motor: wheel '{wheel.id}' "
        + f"(actuator '{wheel.actuator_ref}'), gear {wheel.gear_ratio}:1.\n"
        + "MotorParams is homogeneous; per-wheel differences are not captured.")
    for f in estimated_fields:
        cm.yaml_add_eol_comment("ESTIMATED, not from datasheet", f)
    return cm


def _nominal_map(inp: BuildInputs, true_map: CommentedMap) -> CommentedMap:
    me = inp.model_error
    if me.mode == "manual":
        # hand-written nominal takes over entirely (true/nominal stay independent)
        manual_path = inp.base_dir / me.manual_file
        doc = rt_load(manual_path)
        if isinstance(doc, CommentedMap):
            doc.yaml_set_start_comment(
                GENERATED_HEADER + f"\nCopied verbatim from {me.manual_file} "
                "(model_error mode: manual).")
        return doc

    # ratio mode: nominal = true * ratio, for the first-order model's Jn, Bn.
    r = me.ratios
    jn = float(true_map["inertia_kgm2"]) * float(r.get("inertia_kgm2", 1.0))
    bn = float(true_map["damping_nms"]) * float(r.get("damping_nms", 1.0))
    cm = CommentedMap({"inertia_kgm2": jn, "damping_nms": bn})
    note = (GENERATED_HEADER
            + "\nNominal first-order model 1/(Jn s + Bn) = true * model_error ratios."
            + f"\nratios: inertia={r.get('inertia_kgm2', 1.0)}, "
            + f"damping={r.get('damping_nms', 1.0)}.")
    if float(r.get("torque_constant_nm_a", 1.0)) != 1.0:
        note += ("\nNote: torque_constant ratio is not representable in the "
                 "first-order nominal and was ignored.")
    cm.yaml_set_start_comment(note)
    return cm


def _jacobian_map(inp: BuildInputs) -> CommentedMap:
    dj = DriveJacobian(inp.chassis)
    rows = CommentedMap()
    for w, row in zip(inp.chassis.drive_wheels, dj.J):
        rows[w.id] = [float(x) for x in row]
    cm = CommentedMap({
        "schema_version": 1,
        "maps": "body_twist [vx, vy, wz] -> per-wheel motor-shaft angular velocity [rad/s]",
        "condition_number": float(dj.condition_number),
        "rows": rows,
    })
    cm.yaml_set_start_comment(
        GENERATED_HEADER + "\nDrive jacobian for cross-checking the layout.")
    return cm


@dataclass
class BuildResult:
    plant_true: Path
    plant_nominal: Path
    jacobian: Path


def build(base_dir: str | Path = ".") -> BuildResult:
    inp = load_inputs(base_dir)
    out_dir = Path(base_dir) / "config" / "generated"

    true_map = _motor_params_map(inp)
    nominal_map = _nominal_map(inp, true_map)
    jac_map = _jacobian_map(inp)

    p_true = out_dir / "plant_true.yaml"
    p_nom = out_dir / "plant_nominal.yaml"
    p_jac = out_dir / "jacobian.yaml"
    rt_dump(true_map, p_true)
    rt_dump(nominal_map, p_nom)
    rt_dump(jac_map, p_jac)
    return BuildResult(plant_true=p_true, plant_nominal=p_nom, jacobian=p_jac)
