"""The Gazebo hand-off.

This export exists because a number can be right in omni_sim and wrong by the
gear ratio the moment it is copied into another tool -- which is the 5.9x error
this project already shipped once. So the tests are mostly about the
conversion being right and about the tool *refusing* rather than guessing.
"""
from __future__ import annotations

from pathlib import Path

import numpy as np
import pytest
import yaml

from omni_sim_core.export.gazebo_actuator import (ExportError, export_actuator_config,
                                                  sdf_snippet, wheel_limits)

ROOT = Path(__file__).resolve().parents[2]
PLANT = ROOT / "config" / "generated" / "plant_true.yaml"
CHASSIS = ROOT / "config" / "robot" / "chassis.yaml"

pytestmark = pytest.mark.skipif(not (PLANT.exists() and CHASSIS.exists()),
                                reason="repo config/ not available")


def test_the_gear_ratio_is_applied_in_both_directions():
    """Reduction multiplies torque and divides speed. Getting the direction
    backwards is as wrong as omitting it, and looks just as plausible."""
    lim = wheel_limits(motor_stall_torque_nm=4.0, motor_no_load_rad_s=60.0,
                       gear_ratio=6.0, wheel_radius_m=0.05)
    assert lim.effort_limit_nm == pytest.approx(24.0)
    assert lim.velocity_limit_rad_s == pytest.approx(10.0)
    assert lim.wheel_surface_speed_ms == pytest.approx(0.5)


def test_it_refuses_rather_than_assuming_one_to_one(tmp_path):
    """A plant file carries motor-shaft numbers and mentions the gear ratio
    only in a comment. Defaulting to 1:1 would export those numbers as wheel
    limits -- wrong by exactly the ratio, and silent."""
    with pytest.raises(ExportError, match="1:1"):
        export_actuator_config(PLANT, tmp_path / "out.yaml")


def test_it_refuses_a_mixed_drivetrain(tmp_path):
    """One joint limit cannot describe wheels with different gearing."""
    from omni_sim_core.mechanism.yaml_rt import rt_dump, rt_load

    doc = rt_load(CHASSIS)
    doc["drive_wheels"][0]["gear_ratio"] = 3.0      # one wheel differs
    mixed = tmp_path / "chassis.yaml"
    rt_dump(doc, mixed)
    with pytest.raises(ExportError, match="mixed"):
        export_actuator_config(PLANT, tmp_path / "out.yaml", chassis_yaml=mixed)


def test_a_bad_plant_file_is_rejected(tmp_path):
    bad = tmp_path / "plant.yaml"
    bad.write_text("n_motors: 4\n")
    with pytest.raises(ExportError, match="torque_max_nm"):
        export_actuator_config(bad, tmp_path / "out.yaml",
                               gear_ratio=2.0, wheel_radius_m=0.05)


def test_the_export_matches_what_the_simulator_does(tmp_path):
    """The round trip that makes this worth having: the exported body speed
    must be the speed omni_sim itself says the drivetrain reaches.

    ``achievable_speed`` carries a margin for accelerating, so it is compared
    against the exported (unmargined) figure scaled by that same margin.
    """
    from omni_sim_core.mechanism.robot_config import (achievable_speed,
                                                      robot_config_from_dir)

    lim = export_actuator_config(PLANT, tmp_path / "out.yaml",
                                 chassis_yaml=CHASSIS)
    cfg, _ = robot_config_from_dir(ROOT)
    for direction, exported in ((( 1.0, 0.0, 0.0), lim.body_speed_axis_ms),
                                (( 1.0, 1.0, 0.0), lim.body_speed_diagonal_ms)):
        sim_side = achievable_speed(cfg, direction, margin=1.0)
        assert exported == pytest.approx(sim_side, rel=0.05), (
            f"{direction}: exported {exported:.3f} m/s, simulator "
            f"{sim_side:.3f} m/s")


def test_the_wheel_surface_speed_is_not_the_body_speed(tmp_path):
    """On drive axes at +-45 deg the body travels sqrt(2) faster along an axis
    than the wheel's contact patch does. Reporting the contact patch as "max
    speed" is a quiet 1.41x error of the same family as the gear one."""
    lim = export_actuator_config(PLANT, tmp_path / "out.yaml",
                                 chassis_yaml=CHASSIS)
    assert lim.body_speed_axis_ms == pytest.approx(
        lim.wheel_surface_speed_ms * np.sqrt(2), rel=0.02)
    assert lim.body_speed_diagonal_ms == pytest.approx(
        lim.wheel_surface_speed_ms, rel=0.02)


def test_the_written_files_carry_their_provenance(tmp_path):
    out = tmp_path / "drivetrain.yaml"
    export_actuator_config(PLANT, out, chassis_yaml=CHASSIS)
    text = out.read_text()
    assert "GENERATED by omni_sim_core.export" in text
    assert str(PLANT) in text and str(CHASSIS) in text
    assert "WHEEL JOINT, not the motor shaft" in text

    body = yaml.safe_load(text)
    assert body["joint_velocity_limit"] > 0
    assert body["joint_effort_limit"] > 0
    assert body["drive_joints"] == ["fl", "fr", "rl", "rr"]

    sdf = out.with_suffix(".sdf").read_text()
    assert sdf.count("<joint") == 4
    assert f"{body['joint_effort_limit']:.4f}" in sdf


def test_the_sdf_states_which_shaft_each_number_is():
    """A snippet that gets pasted into someone else's model has to say so on
    its face; that is the whole failure mode being guarded against."""
    lim = wheel_limits(motor_stall_torque_nm=4.0, motor_no_load_rad_s=60.0,
                       gear_ratio=6.0, wheel_radius_m=0.05)
    text = sdf_snippet(lim, ["fl"])
    assert "at the WHEEL" in text and "at the motor" in text


def test_a_sweep_candidate_exports_with_its_body_speeds(tmp_path):
    """The path built for choosing a candidate must carry the number a
    candidate is chosen on. It first did not: passing the gear ratio
    explicitly skipped the chassis, and the body speeds came out null."""
    from omni_sim_core.export.gazebo_actuator import export_sweep_candidate

    lim = export_sweep_candidate(ROOT, tmp_path / "cand.yaml",
                                 gear_ratio=2.0, wheel_radius_m=0.050,
                                 total_mass_kg=15.0)
    assert lim.body_speed_diagonal_ms is not None
    assert lim.body_speed_axis_ms > lim.body_speed_diagonal_ms
    # it is the same drivetrain the sweep evaluated
    from omni_sim_core.mechanism.robot_config import achievable_speed
    from omni_sim_core.sweep.drivetrain import build_variant
    cfg = build_variant(str(ROOT), 2.0, 0.050, 15.0)
    assert lim.body_speed_diagonal_ms == pytest.approx(
        achievable_speed(cfg, (1, 1, 0), margin=1.0), rel=0.02)
    assert (tmp_path / "cand_plant.yaml").exists(), "no plant file written"


def test_the_candidate_meets_the_sweep_requirement_it_was_picked_for(tmp_path):
    """2:1 on a 50 mm wheel is on the sweep's feasible boundary for the 1.0 m/s
    diagonal requirement; 6:1 is the configured drivetrain and is not."""
    from omni_sim_core.export.gazebo_actuator import export_sweep_candidate

    good = export_sweep_candidate(ROOT, tmp_path / "a.yaml",
                                  gear_ratio=2.0, wheel_radius_m=0.050)
    bad = export_sweep_candidate(ROOT, tmp_path / "b.yaml",
                                 gear_ratio=6.0, wheel_radius_m=0.050)
    assert good.body_speed_diagonal_ms >= 1.0
    assert bad.body_speed_diagonal_ms < 1.0
