#!/usr/bin/env python3
"""Turn ``field_2027.yaml`` into ROS ``map_server`` layers + a top-view render.

The 2027 field is three storeys, so one occupancy grid cannot describe it. We
emit one grid per driving surface:

    ground -- what TR sees: field boundary, the L1 slab wall, ramp and stair
              flanks, the Mustika Pillar, the centre divider.
    l1     -- what BR sees once it is up: the perimeter barrier, the L2 slab,
              the hole around the Mustika pocket, the L1 divider.
    l2     -- the 3 x 3 m top deck and the Central Pillar.

Each layer is written as PGM + YAML in the exact format
``env/occupancy_grid.py`` already reads (0 = occupied/black, 255 = free/white,
image row 0 = north, ``origin`` = world coord of the lower-left pixel).

    python maps/gen_field_2027.py                 # all layers + PNG renders
    python maps/gen_field_2027.py --layer ground  # just one
    python maps/gen_field_2027.py --no-png
"""
from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import yaml

FREE = np.uint8(255)
OCC = np.uint8(0)

HERE = Path(__file__).resolve().parent


# --------------------------------------------------------------------------- #
# raster canvas
# --------------------------------------------------------------------------- #
class Canvas:
    """World-metre drawing surface backed by a PGM-valued uint8 raster.

    ``img[0]`` is the NORTH-most row, matching the PGM-on-disk convention that
    ``OccupancyGrid.from_yaml`` undoes with ``np.flipud``.
    """

    def __init__(self, width_m: float, height_m: float, res: float, fill=FREE):
        self.res = res
        self.cols = int(round(width_m / res))
        self.rows = int(round(height_m / res))
        self.img = np.full((self.rows, self.cols), fill, dtype=np.uint8)

    # world -> array indices. y is flipped because row 0 is north.
    def _cols(self, x0: float, x1: float) -> slice:
        return slice(max(0, int(round(x0 / self.res))),
                     min(self.cols, int(round(x1 / self.res))))

    def _rows(self, y0: float, y1: float) -> slice:
        return slice(max(0, self.rows - int(round(y1 / self.res))),
                     min(self.rows, self.rows - int(round(y0 / self.res))))

    def rect(self, r, value) -> None:
        x0, y0, x1, y1 = r
        self.img[self._rows(y0, y1), self._cols(x0, x1)] = value

    def outline(self, r, t: float, value) -> None:
        """Frame of thickness ``t`` drawn INSIDE rect ``r``."""
        x0, y0, x1, y1 = r
        self.rect((x0, y0, x1, y0 + t), value)
        self.rect((x0, y1 - t, x1, y1), value)
        self.rect((x0, y0, x0 + t, y1), value)
        self.rect((x1 - t, y0, x1, y1), value)

    def border(self, t: float, value) -> None:
        self.outline((0, 0, self.cols * self.res, self.rows * self.res), t, value)

    def circle(self, center, diameter: float, value) -> None:
        cx, cy = center
        r = diameter / 2.0
        ys = (self.rows - 0.5 - np.arange(self.rows)) * self.res
        xs = (np.arange(self.cols) + 0.5) * self.res
        mask = (xs[None, :] - cx) ** 2 + (ys[:, None] - cy) ** 2 <= r * r
        self.img[mask] = value

    def segment(self, seg, t: float, value) -> None:
        """Axis-aligned fence segment of thickness ``t``, centred on the line."""
        x0, y0, x1, y1 = seg
        h = t / 2.0
        self.rect((min(x0, x1) - h, min(y0, y1) - h,
                   max(x0, x1) + h, max(y0, y1) + h), value)

    # -- output ------------------------------------------------------------- #
    def write(self, stem: Path, origin=(0.0, 0.0, 0.0)) -> None:
        pgm = stem.with_suffix(".pgm")
        with open(pgm, "wb") as f:
            f.write(b"P5\n")
            f.write(f"# {stem.name} -- generated by gen_field_2027.py\n".encode())
            f.write(f"{self.cols} {self.rows}\n255\n".encode())
            f.write(self.img.tobytes())
        stem.with_suffix(".yaml").write_text(
            f"image: {pgm.name}\n"
            f"resolution: {self.res}\n"
            f"origin: [{origin[0]}, {origin[1]}, {origin[2]}]\n"
            "negate: 0\n"
            "occupied_thresh: 0.65\n"
            "free_thresh: 0.196\n"
        )


# --------------------------------------------------------------------------- #
# layers
# --------------------------------------------------------------------------- #
def _rects(node):
    """Flatten any of the shapes the spec uses into a list of [x0,y0,x1,y1].

    Handles ``{rect: [...]}``, ``{red: ..., blue: ...}``, a list of either, and
    a bare rect.
    """
    if isinstance(node, dict):
        if "rect" in node:
            return [node["rect"]]
        return [r for v in node.values() for r in _rects(v)]
    if isinstance(node, list) and node and isinstance(node[0], (dict, list)):
        return [r for v in node for r in _rects(v)]
    return [node]


def build_ground(spec) -> Canvas:
    w, h = spec["field"]["size"]
    t = spec["meta"]["wall_thickness"]
    c = Canvas(w, h, spec["meta"]["resolution"])

    c.border(t, OCC)                                   # game field boundary
    c.rect(spec["platforms"]["l1"]["rect"], OCC)       # the L1 slab is a wall
    for n in spec["notches"].values():                 # ...except the pocket,
        c.rect(n["rect"], FREE)                        # which is ground
    for r in spec["ramps"].values():
        c.rect(r["rect"], OCC)                         # TR cannot climb these
    for s in spec["stairs"].values():
        if s["from"] == "ground":
            c.rect(s["rect"], OCC)
    p = spec["pillars"]["mustika"]
    c.circle(p["center"], p["diameter"], OCC)
    for f in spec["fences"]["center_divider_ground"]:
        c.segment(f["seg"], t, OCC)
    return c


def build_l1(spec) -> Canvas:
    w, h = spec["field"]["size"]
    t = spec["meta"]["wall_thickness"]
    c = Canvas(w, h, spec["meta"]["resolution"], fill=OCC)   # off-slab = a drop

    c.rect(spec["platforms"]["l1"]["rect"], FREE)
    for n in spec["notches"].values():
        c.rect(n["rect"], OCC)                          # hole down to ground
    c.rect(spec["platforms"]["l2"]["rect"], OCC)        # the L2 slab is a wall
    c.outline(spec["platforms"]["l1"]["rect"], t, OCC)  # perimeter barrier
    for z in _rects(spec["zones"]["transfer"]):         # ...open at the handover
        c.rect(z, FREE)
    for f in spec["fences"]["center_divider_l1"]:
        c.segment(f["seg"], t, OCC)
    return c


def build_l2(spec) -> Canvas:
    w, h = spec["field"]["size"]
    c = Canvas(w, h, spec["meta"]["resolution"], fill=OCC)
    c.rect(spec["platforms"]["l2"]["rect"], FREE)
    p = spec["pillars"]["central"]
    c.circle(p["center"], p["diameter"], OCC)
    return c


BUILDERS = {"ground": build_ground, "l1": build_l1, "l2": build_l2}


# --------------------------------------------------------------------------- #
# renders
# --------------------------------------------------------------------------- #
def render_overview(spec, out: Path) -> None:
    """Colour top view, painted in rulebook section-14 RGB."""
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    from matplotlib.patches import Circle, Rectangle

    col = {k: tuple(v / 255 for v in rgb) for k, rgb in spec["colors"].items()}
    W, H = spec["field"]["size"]
    cx = spec["field"]["center_x"]

    fig, ax = plt.subplots(figsize=(11, 11))

    def box(r, c, z=1, ec="none", lw=0, hatch=None, alpha=1.0):
        x0, y0, x1, y1 = r
        ax.add_patch(Rectangle((x0, y0), x1 - x0, y1 - y0, facecolor=c,
                               edgecolor=ec, lw=lw, zorder=z, hatch=hatch,
                               alpha=alpha))

    def label(x, y, s, z=9, size=8, c="0.15", weight="normal"):
        ax.text(x, y, s, ha="center", va="center", fontsize=size, color=c,
                zorder=z, weight=weight)

    # ground
    box((0, 0, cx, H), col["ground_red"], 1)
    box((cx, 0, W, H), col["ground_blue"], 1)
    box(spec["zones"]["ground_shared"]["rect"], col["ground_shared"], 2,
        ec="0.4", lw=0.8)
    for team in ("red", "blue"):
        box(spec["zones"]["storage"][team]["rect"], col[f"ground_{team}"], 2,
            ec="0.35", lw=1.2)
        for r in _rects(spec["zones"]["start"][team]):
            box(r, col[f"start_{team}"], 3)
        box(spec["ramps"][team]["rect"], col[f"ramp_{team}"], 3, ec="0.4", lw=0.6)

    # 20 Earth Blocks per team: 5 x 2 columns stacked two high -- exactly what
    # a 1000 x 2000 Storage Area holds at 350 mm pitch [R 4.1.3]
    eb = spec["objects"]["earth_block"]["size"]
    for team in ("red", "blue"):
        x0, y0, x1, y1 = spec["zones"]["storage"][team]["rect"]
        for i in range(5):
            for j in range(2):
                bx, by = x0 + 0.05 + i * (eb + 0.03), y0 + 0.1 + j * (eb + 0.05)
                box((bx, by, bx + eb, by + eb), col[f"start_{team}"], 2.5,
                    ec="0.2", lw=0.5, alpha=0.85)

    # 12 Sky Blocks on the 5 x 5 chessboard, centre cell empty [R 4.1.4, Fig 4]
    sb = spec["objects"]["sky_block"]["size"]
    gx0, gy0, gx1, gy1 = spec["zones"]["ground_shared"]["rect"]
    pitch = (gx1 - gx0) / 5.0
    for i in range(5):
        for j in range(5):
            if (i + j) % 2 or (i, j) == (2, 2):
                continue
            bx = gx0 + (i + 0.5) * pitch - sb / 2
            by = gy0 + (j + 0.5) * pitch - sb / 2
            face = "start_red" if i < 2 else ("start_blue" if i > 2 else
                                              ("start_red" if j < 2 else "start_blue"))
            box((bx, by, bx + sb, by + sb), col[face], 2.6, ec="0.2", lw=0.5)

    # stairs, drawn tread by tread so the direction of travel is visible
    for name, s in spec["stairs"].items():
        team = "red" if name.endswith("red") else "blue"
        x0, y0, x1, y1 = s["rect"]
        base = col[f"l1_{team}"]
        for i in range(s["steps"]):
            f = i / max(1, s["steps"] - 1)
            shade = tuple(c * (0.72 + 0.28 * (1 - f)) for c in base)
            if s["to"] == "l1":       # runs north, up towards the slab
                yy0 = y0 + (y1 - y0) * i / s["steps"]
                box((x0, yy0, x1, yy0 + (y1 - y0) / s["steps"]), shade, 4,
                    ec="0.45", lw=0.4)
            else:                     # runs east/west towards L2
                sign = 1 if team == "red" else -1
                span = (x1 - x0) / s["steps"]
                xx0 = (x0 + span * i) if sign > 0 else (x1 - span * (i + 1))
                box((xx0, y0, xx0 + span, y1), shade, 6, ec="0.45", lw=0.4)

    # L1
    l1 = spec["platforms"]["l1"]["rect"]
    box(l1, col["l1_red"], 5)
    box((cx, l1[1], l1[2], l1[3]), col["l1_blue"], 5)
    for r in _rects(spec["zones"]["l1_shared"]):
        box(r, col["l1_shared"], 5.5)
    box(l1, "none", 5.6, ec=tuple(c * 0.75 for c in col["barrier"]), lw=3)
    for team in ("red", "blue"):
        box(spec["zones"]["transfer"][team]["rect"], col[f"transfer_{team}"], 6,
            ec="0.3", lw=1.0)
        box(spec["zones"]["retry_l1"][team]["rect"], col[f"start_{team}"], 6)

    # the pocket punched through L1, and the pillar standing in it
    for n in spec["notches"].values():
        box(n["rect"], col["ground_shared"], 6, ec="0.35", lw=1.0)

    # L2
    l2 = spec["platforms"]["l2"]["rect"]
    box(l2, col["l2_area"], 7, ec="0.35", lw=2)

    # building spots
    ssz = spec["building_spots"]["size"]
    for key, pts in spec["building_spots"].items():
        if key == "size":
            continue
        for x, y in pts:
            box((x - ssz / 2, y - ssz / 2, x + ssz / 2, y + ssz / 2),
                col["building_spot"], 8, ec="0.15", lw=0.8)

    # pillars
    for name, p in spec["pillars"].items():
        ax.add_patch(Circle(p["center"], p["diameter"] / 2,
                            facecolor=col["pillar"], edgecolor="0.1",
                            lw=1.0, zorder=9))
        ax.add_patch(Circle(p["center"], 0.180 / 2, facecolor="#e8c33a",
                            edgecolor="0.1", lw=0.6, zorder=9.1))

    # fences
    for key in ("center_divider_ground", "center_divider_l1"):
        for f in spec["fences"][key]:
            x0, y0, x1, y1 = f["seg"]
            ax.plot([x0, x1], [y0, y1], color=col["boundary"], lw=4,
                    solid_capstyle="butt",
                    zorder=6.5 if key.endswith("l1") else 4.5)

    # labels
    label(1.7, 10.6, "STORAGE (R) -- 20 Earth Blocks", size=7)
    label(9.3, 10.6, "STORAGE (B) -- 20 Earth Blocks", size=7)
    label(1.5, 1.6, "START / RETRY", size=7)
    label(9.5, 1.6, "START / RETRY", size=7)
    label(5.5, 2.42, "GROUND SHARED -- 12 Sky", size=6.5, c="0.2")
    label(5.5, 8.68, "MUSTIKA PILLAR", size=6.5, c="0.15", weight="bold")
    label(5.5, 5.12, "CENTRAL PILLAR", size=6.5, c="0.1", z=9.5)
    label(2.0, 6.25, "RAMP", size=7)
    label(9.0, 6.25, "RAMP", size=7)
    label(3.5, 1.9, "STAIRS", size=6.5)
    label(7.5, 1.9, "STAIRS", size=6.5)
    label(3.0, 3.7, "TRANSFER", size=6.5, c="0.1")
    label(8.0, 3.7, "TRANSFER", size=6.5, c="0.1")
    label(3.05, 7.95, "L1 RETRY", size=6, c="w")
    label(7.95, 7.95, "L1 RETRY", size=6, c="w")
    label(3.3, 2.75, "LEVEL 1  (+600)", size=8, c="0.25", weight="bold")
    label(5.5, 4.35, "LEVEL 2  (+900)", size=8, c="0.25", weight="bold")
    label(0.9, 5.5, "GROUND / RED", size=8, c="0.35", weight="bold")
    label(10.1, 5.5, "GROUND / BLUE", size=8, c="0.35", weight="bold")

    ax.add_patch(Rectangle((0, 0), W, H, facecolor="none",
                           edgecolor=col["boundary"], lw=5, zorder=10))
    ax.set_xlim(-0.4, W + 0.4)
    ax.set_ylim(-0.4, H + 0.4)
    ax.set_aspect("equal")
    ax.set_xticks(range(0, 12))
    ax.set_yticks(range(0, 12))
    ax.grid(True, ls=":", lw=0.4, color="0.6", zorder=0.5)
    ax.set_xlabel("x [m]  (+x = east = blue)")
    ax.set_ylabel("y [m]  (+y = north)")
    ax.set_title("ABU Robocon 2027 -- field, top view\n"
                 "11 x 11 m  |  spec: field_2027.yaml  |  rulebook "
                 + str(spec["meta"]["rulebook"]), fontsize=11)
    fig.tight_layout()
    fig.savefig(out, dpi=130)
    plt.close(fig)


def render_layers(canvases, spec, out: Path) -> None:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    W, H = spec["field"]["size"]
    fig, axes = plt.subplots(1, len(canvases), figsize=(5 * len(canvases), 5.6))
    axes = np.atleast_1d(axes)
    for ax, (name, c) in zip(axes, canvases.items()):
        occ = (c.img == OCC).sum()
        ax.imshow(c.img, cmap="gray", vmin=0, vmax=255,
                  extent=(0, W, 0, H), interpolation="nearest")
        ax.set_title(f"{name}  ({c.cols}x{c.rows} @ {c.res} m/cell)\n"
                     f"{occ / c.img.size:.0%} occupied", fontsize=10)
        ax.set_aspect("equal")
        ax.set_xlabel("x [m]")
        ax.grid(True, ls=":", lw=0.4, color="tab:cyan", alpha=0.5)
    axes[0].set_ylabel("y [m]")
    fig.suptitle("Generated occupancy layers (black = occupied)", fontsize=12)
    fig.tight_layout()
    fig.savefig(out, dpi=130)
    plt.close(fig)


# --------------------------------------------------------------------------- #
def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--spec", type=Path, default=HERE / "field_2027.yaml")
    ap.add_argument("--out-dir", type=Path, default=HERE)
    ap.add_argument("--layer", choices=list(BUILDERS), action="append",
                    help="repeatable; default = all")
    ap.add_argument("--resolution", type=float,
                    help="override meta.resolution [m/cell]")
    ap.add_argument("--no-png", action="store_true")
    args = ap.parse_args()

    spec = yaml.safe_load(args.spec.read_text(encoding="utf-8"))
    if args.resolution:
        spec["meta"]["resolution"] = args.resolution
    args.out_dir.mkdir(parents=True, exist_ok=True)

    layers = args.layer or list(BUILDERS)
    canvases = {}
    for name in layers:
        c = BUILDERS[name](spec)
        stem = args.out_dir / f"field_2027_{name}"
        c.write(stem)
        canvases[name] = c
        print(f"{stem.name}.pgm  {c.cols}x{c.rows} @ {c.res} m/cell  "
              f"occupied {(c.img == OCC).mean():.1%}")

    if not args.no_png:
        ov = args.out_dir / "field_2027_overview.png"
        render_overview(spec, ov)
        print(ov.name)
        ly = args.out_dir / "field_2027_layers.png"
        render_layers(canvases, spec, ly)
        print(ly.name)


if __name__ == "__main__":
    main()
