"""Ground / L1 / L2 level switching + territory + collision for the ABU
Robocon 2027 field.

Two rules the first cut of this got wrong (both real rule violations, not
just "looks odd"):

1. A robot could climb from Ground onto L1 anywhere along L1's edge, not
   only through its own team's Ramp -- because the level was recomputed
   fresh from raw position every step, with no memory of *how* it got there.
   Fixed by making the level persistent state that only changes while the
   robot is inside a Ramp (Ground<->L1) or Stairs (L1<->L2) gate rectangle
   (``field_layout_2027.RAMP_RECT_MM`` / ``STAIRS_GATE_RECT_MM``).

2. Nothing stopped a robot from driving straight across the centre divider
   into the opponent's half -- rule 6.2.2 (Zone Violation, "Opponent's
   Territory"). Fixed with a territory check: on Ground and L1 a robot must
   stay on its own side of ``CENTER_X_MM`` unless it's inside a Shared Area
   (Ground Shared, the area around the Mustika Pillar, or the L1 Shared
   strip); L2 is fully shared so territory never applies there.

Three occupancy grids still share one (x, y) world frame --
``maps/field_2027_{ground,l1,l2}.yaml``, generated by ``experiments/gen_field.py``
from ``config/field/robocon2027.yaml`` -- each one marking "not on this
level's own footprint" as occupied/lethal (``field/slicer.py``).

This is a visual/demo-only convenience for ``ui/viewer.py`` -- it does not
touch ``RobotSim`` itself, so the Phase 0/1 acceptance tests are unaffected.
"""
from __future__ import annotations

import numpy as np

from ..env.occupancy_grid import OCCUPIED, OccupancyGrid
from ..sensors.lidar import Lidar, LidarParams
from .field_layout_2027 import (
    CENTER_X_MM, GROUND_SHARED_RECT_MM, MUSTIKA_SHARED_RECT_MM,
    L1_SHARED_STRIP_MM, RAMP_GATE_RECT_MM, STAIRS_GATE_MARGIN_MM, _mirror,
)

CENTER_X_M = CENTER_X_MM / 1000.0
LEVEL_ORDER = ("ground", "l1", "l2")

# Waypoints used to stitch a multi-level A* plan through each gate: a point
# on the "from" level's own free area and one on the "to" level's, both clear
# of the planner's hard inflation radius on their *own* grid. The segment
# between them is the part no grid clears -- the robot is on the slope, on
# neither floor -- so it is covered by the gate rectangles instead.
#
# These are not free parameters. Each is pinned to the measured free band of
# the level it belongs to at the real chassis radius (r_circ 0.636 m for the
# 0.9 m square), so they move if the chassis or the field spec changes:
#
#   ramp, ground side  x <= 1.889   (L1 slab wall at 2.525, minus r_circ)
#   ramp, L1 side      x >= 2.136   (ramp's west end at 1.500, plus r_circ)
#   stairs, L1 side    y in [3.136, 3.364] and x <= 4.864
#                      (the L1 ring: 1.5 m between the L1 and L2 slab edges,
#                       leaving 0.228 m after inflating both sides; its east
#                       end is where the divider_l1 fence stub blocks it)
#   stairs, L2 side    y >= 4.636   (L2 slab edge at 4.000, plus r_circ)
#
# The stairs pair sits at x=4.8 rather than the gate's centre x=5.5 for that
# last reason: the centre divider fence makes the middle of the ring lethal,
# so the only reachable part of the Stairs gate is its western sliver.
# Re-measure with ``scripts/measure_corridors.py`` after changing either.
_RAMP_WAYPOINTS_M = {
    "red": ((1.8, 4.75), (2.4, 4.75)),
    "blue": ((9.2, 4.75), (8.6, 4.75)),
}
_STAIRS_WAYPOINTS_M = ((4.8, 3.25), (4.8, 4.70))


def _rect_m(rect_mm: tuple[float, float, float, float]) -> tuple[float, float, float, float]:
    return tuple(v / 1000.0 for v in rect_mm)


def _inside(x: float, y: float, rect: tuple[float, float, float, float]) -> bool:
    x0, y0, x1, y1 = rect
    return x0 <= x <= x1 and y0 <= y <= y1


# gate rectangles a level transition is allowed through (metres), per team
_RAMP_M = {"red": _rect_m(RAMP_GATE_RECT_MM), "blue": _rect_m(_mirror(RAMP_GATE_RECT_MM))}
_STAIRS_M = _rect_m(STAIRS_GATE_MARGIN_MM)

# shared-area rectangles where crossing the centre line is legal (metres)
_GROUND_SHARED_M = (_rect_m(GROUND_SHARED_RECT_MM), _rect_m(MUSTIKA_SHARED_RECT_MM))
_L1_SHARED_M = (_rect_m(L1_SHARED_STRIP_MM),)


class LeveledField:
    """Three (grid, LiDAR) pairs, plus the stateful level/territory rules."""

    def __init__(self, ground_yaml: str, l1_yaml: str, l2_yaml: str,
                 team: str = "red", seed: int = 0, n_beams: int = 240) -> None:
        if team not in ("red", "blue"):
            raise ValueError(f"team must be 'red' or 'blue', got {team!r}")
        self.team = team
        self.grids = {
            "ground": OccupancyGrid.from_yaml(ground_yaml),
            "l1": OccupancyGrid.from_yaml(l1_yaml),
            "l2": OccupancyGrid.from_yaml(l2_yaml),
        }
        self.lidars = {
            name: Lidar(LidarParams(n_beams=n_beams, enable_motion_distortion=False),
                        grid, np.random.default_rng(seed + i))
            for i, (name, grid) in enumerate(self.grids.items())
        }
        # The crossing under way, if any: (level being left, level being
        # entered). Only this pair may commit a level change when the centre
        # leaves the gate -- see resolve_level.
        self._gate_pending: tuple[str, str] | None = None

        # "Is this cell free?" and "is any cell within one of it free?", as
        # plain boolean arrays. The collision check runs on a few hundred
        # outline samples, and doing the one-cell tolerance as nine separate
        # offset lookups per sample cost more than everything else put
        # together; dilating once here turns it into a single lookup.
        from scipy.ndimage import binary_dilation
        self._free_lut = {}
        for name, grid in self.grids.items():
            free = grid.grid == 0
            self._free_lut[name] = (free, binary_dilation(free,
                                                          np.ones((3, 3), bool)))

    @staticmethod
    def _free_nearby(grid: OccupancyGrid, x: float, y: float, radius_cells: int = 1) -> bool:
        """Free at (x, y) or within a small neighbourhood (bridges the 1-cell
        seam between two independently-rasterised layer boundaries)."""
        row, col = grid.world_to_grid(x, y)
        for dr in range(-radius_cells, radius_cells + 1):
            for dc in range(-radius_cells, radius_cells + 1):
                r, c = row + dr, col + dc
                if grid.in_bounds(r, c) and not grid.is_occupied(r, c):
                    return True
        return False

    def _in_gate(self, from_level: str, to_level: str, x: float, y: float) -> bool:
        if {from_level, to_level} == {"ground", "l1"}:
            return _inside(x, y, _RAMP_M[self.team])
        if {from_level, to_level} == {"l1", "l2"}:
            return _inside(x, y, _STAIRS_M)
        return False

    def resolve_level(self, current_level: str, x: float, y: float
                       ) -> tuple[str, tuple[str, ...]]:
        """Return ``(state_level, collision_levels)`` for this step.

        Climbing onto L1 is only possible via the Ramp, L1<->L2 only via the
        Stairs gate -- everywhere else the level is a hard wall. Gating this
        on the *centre point* reaching the far, already-clear side of the
        gate doesn't work: a rotated 0.9 m-wide footprint's leading corner
        reaches the boundary up to half a body-width before the centre does,
        so it would be judged against the old level (a wall there) and get
        stuck well short of where a centre-only switch could ever fire.

        So: while the centre is anywhere inside the gate rectangle, both the
        current and the adjacent level are "in play" for collision (a corner
        is fine as long as it clears *either* one), and the committed state
        level doesn't change yet. Once the centre clears the gate rectangle,
        the crossing is over and the state commits to whichever level is
        actually free at the centre now (preferring the higher one).

        This is why each gate rectangle (``field_layout_2027.RAMP_GATE_RECT_MM``
        / ``STAIRS_GATE_MARGIN_MM``) is deliberately generous *only* in the
        direction actually being crossed (x for the Ramp, y for the Stairs)
        and left at the real, narrow width in the other direction (the
        Ramp's own y-span, the Stairs' own x-span): widening it in the
        cross-direction too once let the centre linger "in gate" for long
        enough, over enough lateral distance, that a big heading swing could
        carry a far corner into a *third*, ungated level that was never
        supposed to be in play for this crossing.

        The commit at the end of a crossing is restricted to *the gate that
        was being crossed*, remembered in ``_gate_pending``. It used to be
        "whichever level is free at the centre now, preferring the higher
        one", which quietly threw away the whole rule: drive east into the L1
        slab anywhere along its 6 m wall, and the moment the centre passed
        x = 2.500 the L1 grid was free there, so the robot was declared to be
        *on* L1 and judged against L1 alone -- where standing on the slab is
        perfectly legal. The 600 mm wall stopped nothing. On screen the body
        sank into the wall and then drove along the top of it, 4.5 m from the
        nearest Ramp.
        """
        order = list(LEVEL_ORDER)
        i = order.index(current_level)
        for j in (i + 1, i - 1):
            if 0 <= j < len(order):
                candidate = order[j]
                if self._in_gate(current_level, candidate, x, y):
                    self._gate_pending = (current_level, candidate)
                    return current_level, (current_level, candidate)

        # Outside every gate. A level change may only *finish* here, and only
        # for the crossing that was actually under way.
        pending, self._gate_pending = self._gate_pending, None
        if pending is not None:
            leaving, entering = pending
            if (not self._free_nearby(self.grids[leaving], x, y)
                    and self._free_nearby(self.grids[entering], x, y)):
                return entering, (entering,)
        return current_level, (current_level,)

    def level_of(self, x: float, y: float) -> str:
        """Which level's own grid recognises (x, y) as on its footprint,
        preferring the higher one (an L2 point is technically also "not
        lethal" on the ground grid below it, but it's on L2)."""
        for lvl in ("l2", "l1", "ground"):
            if self._free_nearby(self.grids[lvl], x, y):
                return lvl
        return "ground"

    def transition_waypoint_pair(self, from_level: str, to_level: str
                                  ) -> tuple[tuple[float, float], tuple[float, float]]:
        """``(point_on_from_level, point_on_to_level)`` for the gate directly
        connecting two *adjacent* levels -- used to stitch a multi-level plan
        into single-level A* segments (ground<->l1 via the Ramp, l1<->l2 via
        the Stairs). Raises if the levels aren't adjacent (plan the chain
        through the intermediate level instead)."""
        if {from_level, to_level} == {"ground", "l1"}:
            pts = _RAMP_WAYPOINTS_M[self.team]
        elif {from_level, to_level} == {"l1", "l2"}:
            pts = _STAIRS_WAYPOINTS_M
        else:
            raise ValueError(f"{from_level!r} and {to_level!r} aren't adjacent levels")
        i, j = LEVEL_ORDER.index(from_level), LEVEL_ORDER.index(to_level)
        return pts if i < j else (pts[1], pts[0])

    def in_shared_area(self, level: str, x: float, y: float) -> bool:
        if level == "l2":
            return True  # L2 Shared Area: the whole platform
        if level == "ground":
            return any(_inside(x, y, r) for r in _GROUND_SHARED_M)
        if level == "l1":
            return any(_inside(x, y, r) for r in _L1_SHARED_M)
        return False

    def territory_ok(self, level: str, x: float, y: float) -> bool:
        """Rule 6.2.2: no crossing into the opponent's half outside a Shared
        Area. Ground and L1 are split red/blue; L2 has no split to violate."""
        if level == "l2" or self.in_shared_area(level, x, y):
            return True
        on_red_side = x <= CENTER_X_M
        return on_red_side if self.team == "red" else not on_red_side

    def territory_masked_grid(self, level: str) -> OccupancyGrid:
        """``level``'s grid with the opponent's half stamped occupied.

        Plan on this, judge with ``self.grids`` -- they are the same geometry
        plus one rule the raster cannot express. Until this existed the two
        sides disagreed about rule 6.2.2: ``is_blocked`` refuses to let the
        robot leave its own half, but A* sees only an occupancy grid, which
        has no notion of teams. Asked for a goal whose shortest route crossed
        the centre line, the planner happily returned it -- a 29 m path around
        the outside of the field -- and the robot then drove a few metres and
        jammed against a wall that exists in no grid, with the plan still
        drawn on screen showing the way "through".

        L2 is returned unmasked: the whole platform is a Shared Area, so there
        is no half to stay on.
        """
        grid = self.grids[level]
        if level == "l2":
            return grid
        res = grid.meta.resolution
        ox, oy, _ = grid.meta.origin
        xs = ox + (np.arange(grid.width) + 0.5) * res
        ys = oy + (np.arange(grid.height) + 0.5) * res
        X, Y = np.meshgrid(xs, ys)

        own = X <= CENTER_X_M if self.team == "red" else X >= CENTER_X_M
        shared = np.zeros_like(own)
        for x0, y0, x1, y1 in (_GROUND_SHARED_M if level == "ground" else _L1_SHARED_M):
            shared |= (X >= x0) & (X <= x1) & (Y >= y0) & (Y <= y1)

        masked = grid.grid.copy()
        masked[~(own | shared)] = OCCUPIED
        return OccupancyGrid(masked, grid.meta)

    def _window(self, poly: np.ndarray):
        """Every grid cell the footprint polygon covers, as a local window.

        Returns ``(inside, X, Y, r0, c0, r1, c1)``: a boolean mask of which
        cells in the window have their centre inside ``poly``, the cells' world
        coordinates, and the window's index range. The window is *not* clipped
        to the grid -- cells off the map stay in it and are treated as occupied
        further down, because the field boundary is a wall like any other.

        This is an area test, not a sampling one. Four corner points were not a
        footprint: a wall thinner than the body (the 30 mm centre divider, the
        50 mm L1 barrier) passed cleanly between two corners with nothing to
        report, and so did any wall corner poking into the middle of an edge --
        the body visibly sank into geometry that was supposed to stop it.
        Sampling the outline densely fixes those two but still cannot see an
        obstacle that ends up wholly inside the body. Rasterising the polygon
        costs the same and has no blind spot at all, so there is nothing left
        to argue about.
        """
        grid = next(iter(self.grids.values()))   # all three share one frame
        res = grid.meta.resolution
        ox, oy, _ = grid.meta.origin
        c0 = int(np.floor((poly[:, 0].min() - ox) / res))
        c1 = int(np.floor((poly[:, 0].max() - ox) / res)) + 2
        r0 = int(np.floor((poly[:, 1].min() - oy) / res))
        r1 = int(np.floor((poly[:, 1].max() - oy) / res)) + 2
        X, Y = np.meshgrid(ox + (np.arange(c0, c1) + 0.5) * res,
                           oy + (np.arange(r0, r1) + 0.5) * res)
        # convex point-in-polygon: the cross product of each edge with the
        # point keeps one sign all the way round (either winding order)
        inside = np.ones(X.shape, dtype=bool)
        cross_pos = np.zeros(X.shape, dtype=bool)
        cross_neg = np.zeros(X.shape, dtype=bool)
        for a, b in zip(poly, np.roll(poly, -1, axis=0)):
            cr = (b[0] - a[0]) * (Y - a[1]) - (b[1] - a[1]) * (X - a[0])
            cross_pos |= cr > 0
            cross_neg |= cr < 0
        inside &= ~(cross_pos & cross_neg)
        return inside, X, Y, r0, c0, r1, c1

    def _free_window(self, level: str, r0: int, c0: int, r1: int, c1: int,
                     tol_cells: int) -> np.ndarray:
        """"This level's grid accepts it", per cell of the window. Cells off
        the map read as occupied."""
        grid = self.grids[level]
        lut = self._free_lut[level][1 if tol_cells else 0]
        ok = np.zeros((r1 - r0, c1 - c0), dtype=bool)
        rr0, rr1 = max(r0, 0), min(r1, grid.height)
        cc0, cc1 = max(c0, 0), min(c1, grid.width)
        if rr1 > rr0 and cc1 > cc0:
            ok[rr0 - r0:rr1 - r0, cc0 - c0:cc1 - c0] = lut[rr0:rr1, cc0:cc1]
        return ok

    def _territory_window(self, level: str, X: np.ndarray,
                          Y: np.ndarray) -> np.ndarray:
        """Vectorised ``territory_ok`` -- rule 6.2.2, per cell."""
        if level == "l2":
            return np.ones(X.shape, dtype=bool)
        rects = _GROUND_SHARED_M if level == "ground" else _L1_SHARED_M
        shared = np.zeros(X.shape, dtype=bool)
        for x0, y0, x1, y1 in rects:
            shared |= (X >= x0) & (X <= x1) & (Y >= y0) & (Y <= y1)
        own = X <= CENTER_X_M if self.team == "red" else X >= CENTER_X_M
        return own | shared

    def is_blocked(self, levels: tuple[str, ...], footprint_world: np.ndarray) -> bool:
        """True if any cell the footprint *covers* is an obstacle, or outside
        the robot's own territory, on *every* level in ``levels``.

        ``footprint_world`` is the polygon's corners (Nx2, m); the area it
        encloses is rasterised here rather than trusted to be empty between
        them.

        Mid-crossing a gate, ``levels`` holds both the level being left and
        the one being entered: a cell only counts as blocked if it fails on
        both. A 0.9 m-wide body straddles a gate for several steps -- checking
        it against a single level would flag the part still on the other side
        as "occupied" (that level's grid marks everywhere outside its own
        footprint as a wall), so nobody could ever finish crossing.

        The one-cell tolerance is applied *only* mid-crossing, which is the
        only place it was ever justified: it bridges the seam between two
        independently rasterised layer boundaries. Granting it everywhere let
        the body overlap every wall in the field by a cell.
        """
        poly = np.asarray(footprint_world, dtype=float)
        inside, X, Y, r0, c0, r1, c1 = self._window(poly)
        tol = 1 if len(levels) > 1 else 0
        ok = np.zeros(inside.shape, dtype=bool)
        for lv in levels:
            ok |= (self._free_window(lv, r0, c0, r1, c1, tol)
                   & self._territory_window(lv, X, Y))
        return bool((inside & ~ok).any())
